srcdir: null #Will be set from cmd line
wrkspdir: null #Will be set from cmd line
datadir: null #Will be set from cmd line
wandb_key: null #Will be set from cmd line
prepared_dataset_dir: null #Will be set from cmd line

hydra_config_dir: src/configs/experiment_test
reference_eval_mode: "blocks_combine-1 blocks_combine-2 blocks_combine-3"


debug: true
weak_gpu: true
do_cleanup: false

train_range: [145, 150]
valid_range: [193, 198]
test_range: [283, 288]

eval_block_side: 64
eval_block_stride: 64
eval_image_side: 684

# References to use in the experiment
do_digital_template_results: true

models:
  # a test network for generator only without encoder
  minimal_l2cond_EpsoniP12iP14:
    yaml: minimal_l2cond_EpsoniP12iP14.yaml
    templates: [o55Epson, o55iP12w]

  #A network combining both generator and encoder in a complicated way
  minimal_l2condtransport_maxinfo_EpsoniP12iP14:
    yaml: minimal_l2condtransport_maxinfo_EpsoniP12iP14.yaml
    templates:
      - [o55Epson, o55iP12w]
      - [o55iP12w, o55Epson]

baseline: minimal_l2cond_EpsoniP12iP14

# what datapairs to use 
captures_used:
  - "o55Epson"
  - "o55iP12w"